---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: 'https://literate.trmnl.7622.me/movies.php?decades={{ decades  | join: "," }}'
polling_headers: ''
polling_body: ''
id: 122948
custom_fields:
- keyname: doesnt_matter
  name: About This Plugin
  field_type: author_bio
  description: Literate Movies shows a random movie from <a target="_blank" href="https://letterboxd.com/shawn_stubbs/list/literate-movies/">this list</a> of movies based on books, short stories, novels, novellas, poems, and other literary works.
  github_url: https://github.com/rknightuk/trmnl-literate-movies
  learn_more_url: https://rknight.me
- keyname: decades
  field_type: select
  name: Decades
  description: Select which decades you would like to see movies from
  options:
  - Any: 1
  - 1910s: 1910
  - 1920s: 1920
  - 1930s: 1930
  - 1940s: 1940
  - 1950s: 1950
  - 1960s: 1960
  - 1970s: 1970
  - 1980s: 1980
  - 1990s: 1990
  - 2000s: 2000
  - 2010s: 2010
  - 2020s: 2020
  multiple: true
name: Literate Movies
refresh_interval: 1440
